C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\models.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\models.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/store/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\accounts\views.py", line 159, in add_store
    return render(request, 'tambah_data.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: tambah_data.html
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/store/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\accounts\views.py", line 155, in add_store
    return redirect('data_tersimpan')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'data_tersimpan' not found. 'data_tersimpan' is not a valid view function or pattern name.
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\smartif.py", line 179, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: '(user.is_seller)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\core\views.py", line 11, in home
    return render(request, 'index.html', {'products': products, 'product_images': product_images})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\defaulttags.py", line 952, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\defaulttags.py", line 885, in __init__
    super().__init__(*args, **kwargs)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\smartif.py", line 181, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\defaulttags.py", line 888, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(user.is_seller)' from '(user.is_seller)'
Internal Server Error: /home/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\core\views.py", line 11, in home
    return render(request, 'index.html', {'products': products, 'product_images': product_images})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dashboard' not found. 'dashboard' is not a valid view function or pattern name.
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\products\models.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\products\models.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\products\models.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dashbord//seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 37, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^
UnboundLocalError: cannot access local variable 'product' where it is not associated with a value
C:\project\advanteyouth\aplication\dashbord\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /dashbord//seller_dashboard/
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 37, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^
UnboundLocalError: cannot access local variable 'product' where it is not associated with a value
Watching for file changes with StatReloader
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 37, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^
UnboundLocalError: cannot access local variable 'product' where it is not associated with a value
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 37, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^
UnboundLocalError: cannot access local variable 'product' where it is not associated with a value
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 37, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^
UnboundLocalError: cannot access local variable 'product' where it is not associated with a value
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 37, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^
UnboundLocalError: cannot access local variable 'product' where it is not associated with a value
Not Found: /dashbord//seller_dashboard/
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 37, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^
UnboundLocalError: cannot access local variable 'product' where it is not associated with a value
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 37, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'store' into field. Choices are: category, description, id, name_product, price, productimage, rasa, slug, store_id, store_id_id, ukuran, upload_date, warna
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 37, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'store' into field. Choices are: category, description, id, name_product, price, productimage, rasa, slug, store_id, store_id_id, ukuran, upload_date, warna
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 52, in seller_dashboard
    product_form = product_form()
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'product_form' where it is not associated with a value
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 52, in seller_dashboard
    product_form = product_form()
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'product_form' where it is not associated with a value
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 53, in seller_dashboard
    product_form = product_form()
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'product_form' where it is not associated with a value
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 53, in seller_dashboard
    product_form = product_form()
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'product_form' where it is not associated with a value
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 53, in seller_dashboard
    product_form = product_form()
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'product_form' where it is not associated with a value
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 53, in seller_dashboard
    product_form = product_form()
                   ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'product_form' where it is not associated with a value
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 55, in seller_dashboard
    return render(request, 'seller_dashboard.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: seller_dashboard.html
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 55, in seller_dashboard
    return render(request, 'seller_dashboard.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: seller_dashboard.html
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 55, in seller_dashboard
    return render(request, 'dashbord/seller_dashboard.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashbord/seller_dashboard.html
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 55, in seller_dashboard
    return render(request, 'dashbord/seller_dashboard.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashbord/seller_dashboard.html
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 55, in seller_dashboard
    return render(request, 'dashbord/seller_dashbord.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashbord/seller_dashboard.html
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /dashbord/seller_dashboard/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\dashbord\views.py", line 38, in seller_dashboard
    products = product.objects.filter(store=store)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'store' into field. Choices are: category, description, id, name_product, price, productimage, rasa, slug, store_id, store_id_id, ukuran, upload_date, warna
C:\project\advanteyouth\aplication\dashbord\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (Permission denied): /products/create_product/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapper_view
    if test_func(request.user):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 78, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /products/create_product/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapper_view
    if test_func(request.user):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 78, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /products/create_product/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapper_view
    if test_func(request.user):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 78, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /products/create_product/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapper_view
    if test_func(request.user):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 78, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /accounts/seller/verification/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapper_view
    if test_func(request.user):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 78, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
Forbidden (Permission denied): /accounts/seller/verification/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapper_view
    if test_func(request.user):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 78, in check_perms
    raise PermissionDenied
django.core.exceptions.PermissionDenied
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing QoiImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Not Found: /admin/accounts/signout
Watching for file changes with StatReloader
Internal Server Error: /accounts/store/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\accounts\views.py", line 155, in add_store
    return redirect('data_tersimpan')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'data_tersimpan' not found. 'data_tersimpan' is not a valid view function or pattern name.
Not Found: /favicon.ico
Internal Server Error: /products/create_product/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\products\views.py", line 24, in create_product
    product_instance.store_id = request.user
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <CustomUser: agungnur123>>": "product.store_id" must be a "Store" instance.
Internal Server Error: /products/create_product/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\products\views.py", line 24, in create_product
    product_instance.store_id = request.user
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <CustomUser: agungnur123>>": "product.store_id" must be a "Store" instance.
Internal Server Error: /products/create_product/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\products\views.py", line 24, in create_product
    product_instance.store_id = request.user
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 266, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <CustomUser: agungnur123>>": "product.store_id" must be a "Store" instance.
C:\project\advanteyouth\aplication\products\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\products\views.py changed, reloading.
Watching for file changes with StatReloader
C:\project\advanteyouth\aplication\products\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /products/create_product/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\project\advanteyouth\env\Lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.IntegrityError: (1048, "Column 'store_id_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\products\views.py", line 25, in create_product
    product_instance.save()
  File "c:\project\advanteyouth\aplication\products\models.py", line 27, in save
    super(product, self).save(*args, **kwargs)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "c:\project\advanteyouth\env\Lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'store_id_id' cannot be null")
C:\project\advanteyouth\aplication\products\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /products/create_product/
Traceback (most recent call last):
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\aplication\products\views.py", line 32, in create_product
    return redirect('my-form')  # Ganti 'my-form' dengan URL yang sesuai
           ^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\project\advanteyouth\env\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'my-form' not found. 'my-form' is not a valid view function or pattern name.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
